ixnes: 6502.cpp PPU.cpp Console.cpp ROM.cpp NROM.cpp IXNES.cpp
	g++ -g -o ixnes 6502.cpp PPU.cpp Console.cpp ROM.cpp NROM.cpp IXNES.cpp -lSDL2

debug: 6502.cpp PPU.cpp Console.cpp ROM.cpp NROM.cpp Debug.cpp
	g++ -g -o debug 6502.cpp PPU.cpp Console.cpp ROM.cpp NROM.cpp Debug.cpp -lSDL2

clean:
	rm ixnes